blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_view, name='blog'),
    path('<int:id>/', views.blog_details, name='blog_details'),
]

django_shopik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import login_view, logout_view, registration_view
from shop.views import shop_search

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls')),
    path('search/<str:sear>/', shop_search, name='shop_search'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    name = models.CharField(max_length=100, unique=True)
    author = models.CharField(max_length=100)
    position = models.PositiveSmallIntegerField()
    image = models.ImageField(upload_to='blogs/%Y/%m/%d', blank=True)
    short_descr = models.TextField(max_length=100)
    descr_paragraph1 = models.TextField(max_length=400, blank=True)
    descr_paragraph2 = models.TextField(max_length=400, blank=True)
    descr_paragraph3 = models.TextField(max_length=400, blank=True)
    descr_paragraph4 = models.TextField(max_length=400, blank=True)
    is_visible = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return f'{self.name}  {self.author}'

blog/views.py
from django.shortcuts import render, get_object_or_404
from shop.models import Category, Subcategory
from blog.models import Blog
from cart.cart import Cart
# Create your views here.


def blog_view(request):
    cart = Cart(request)
    blogs = Blog.objects.filter(is_visible=True)
    categories = Category.objects.filter(is_visible=True)
    subcategories = Subcategory.objects.filter(is_visible=True)
    return render(request,
                  'blog.html',
                  {'blogs': blogs,
                   'cart': cart,
                   'categories': categories,
                   'subcategories': subcategories},
                  )


def blog_details(request, id):
    cart = Cart(request)
    blog = get_object_or_404(Blog, id=id, is_visible=True)
    categories = Category.objects.filter(is_visible=True)
    subcategories = Subcategory.objects.filter(is_visible=True)
    return render(request,
                  'blog-details.html',
                  {'blog': blog,
                   'cart': cart,
                   'categories': categories,
                   'subcategories': subcategories},
                  )

blog/templates/blog-details.html
{% extends 'index.html' %}
{% load static %}
{% block site_content %}


<div class="blog_details">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-12">
                <!--blog grid area start-->
                <div class="blog_wrapper blog_wrapper_details">
                    <article class="single_blog">
                        <figure>
                            <div class="post_header">
                                <h3 class="post_title">{{ blog.name }}</h3>
                                <div class="blog_meta">
                                    <p>Автор : <a href="#">{{ blog.author }}</a> / Від : <a href="#">{{ blog.created }}</a></p>
                                </div>
                            </div>
                            <div class="blog_thumb">
                                <a href="#"><img src={{ blog.image.url }} alt=""></a>
                            </div>
                            <figcaption class="blog_content">
                                <div class="post_content">
                                    <p>{{ blog.descr_paragraph1 }}</p>
                                    <blockquote>
                                        <p>{{ blog.descr_paragraph2 }}</p>
                                    </blockquote>
                                    <p>{{ blog.descr_paragraph3 }}</p>
                                    <p>{{ blog.descr_paragraph4 }}</p>
                                </div>
                            </figcaption>
                        </figure>
                    </article>

                    <div class="comments_box">
                        <h3>3 Comments </h3>
                        <div class="comment_list">
                            <div class="comment_thumb">
                                <img src={% static "assets/img/blog/comment3.png.jpg" %} alt="">
                            </div>
                            <div class="comment_content">
                                <div class="comment_meta">
                                    <h5><a href="#">Admin</a></h5>
                                    <span>October 16, 2018 at 1:38 am</span>
                                </div>
                                <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
                                <div class="comment_reply">
                                    <a href="#">Reply</a>
                                </div>
                            </div>

                        </div>
                        <div class="comment_list list_two">
                            <div class="comment_thumb">
                                <img src={% static "assets/img/blog/comment3.png.jpg" %} alt="">
                            </div>
                            <div class="comment_content">
                                <div class="comment_meta">
                                    <h5><a href="#">Demo</a></h5>
                                    <span>October 16, 2018 at 1:38 am</span>
                                </div>
                                <p>Quisque semper nunc vitae erat pellentesque, ac placerat arcu consectetur</p>
                                <div class="comment_reply">
                                    <a href="#">Reply</a>
                                </div>
                            </div>
                        </div>
                        <div class="comment_list">
                            <div class="comment_thumb">
                                <img src={% static "assets/img/blog/comment3.png.jpg" %} alt="">
                            </div>
                            <div class="comment_content">
                                <div class="comment_meta">
                                    <h5><a href="#">Admin</a></h5>
                                    <span>October 16, 2018 at 1:38 am</span>
                                </div>
                                <p>Quisque orci nibh, porta vitae sagittis sit amet, vehicula vel mauris. Aenean at
                                </p>
                                <div class="comment_reply">
                                    <a href="#">Reply</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="comments_form">
                        <h3>Leave a Reply </h3>
                        <p>Your email address will not be published. Required fields are marked *</p>
                        <form action="#">
                            <div class="row">
                                <div class="col-12">
                                    <label for="review_comment">Comment </label>
                                    <textarea name="comment" id="review_comment"></textarea>
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <label for="author">Name</label>
                                    <input id="author" type="text">

                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <label for="email">Email </label>
                                    <input id="email" type="text">
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <label for="website">Website </label>
                                    <input id="website" type="text">
                                </div>
                            </div>
                            <button class="button" type="submit">Post Comment</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog.html
{% extends 'index.html' %}
{% load static %}
{% block site_content %}


<!--blog area start-->
<div class="blog_page_section mt-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-12">
                <div class="blog_wrapper">
                    {% for blog in blogs %}
                        <article class="single_blog">
                        <figure>
                            <div class="blog_thumb">
                                <a href="{% url "blog:blog_details" blog.id %}"><img src={{ blog.image.url }} alt=""></a>
                            </div>
                            <figcaption class="blog_content">
                                <h4 class="post_title"><a href="{% url "blog:blog_details" blog.id %}"><i class="fa fa-paper-plane"></i>
                                    {{ blog.name }}</a></h4>
                                <div class="blog_meta">
                                    <p>Автор <a href="#">{{ blog.author }}</a> / Дата <a href="#">{{ blog.created }}</a></p>
                                </div>
                                <p class="post_desc">{{ blog.short_descr }}</p>
                                <footer class="btn_more">
                                    <a href="{% url "blog:blog_details" blog.id %}"> Читати більше </a>
                                </footer>
                            </figcaption>
                        </figure>
                    </article>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-3 col-md-12">
                <div class="blog_sidebar_widget">
                    <div class="widget_list widget_search">
                        <div class="widget_title">
                            <h3>Search</h3>
                        </div>
                        <form action="#">
                            <input placeholder="Search..." type="text">
                            <button type="submit">search</button>
                        </form>
                    </div>
                    <div class="widget_list comments">
                        <div class="widget_title">
                            <h3>Recent Comments</h3>
                        </div>
                        <div class="post_wrapper">
                            <div class="post_thumb">
                                <a href="blog-details.html"><img src={% static "assets/img/blog/comment2.png.jpg" %} alt=""></a>
                            </div>
                            <div class="post_info">
                                <span> <a href="#">demo</a> says:</span>
                                <a href="blog-details.html">Quisque semper nunc</a>
                            </div>
                        </div>
                        <div class="post_wrapper">
                            <div class="post_thumb">
                                <a href="blog-details.html"><img src={% static "assets/img/blog/comment2.png.jpg" %} alt=""></a>
                            </div>
                            <div class="post_info">
                                <span><a href="#">admin</a> says:</span>
                                <a href="blog-details.html">Quisque orci porta...</a>
                            </div>
                        </div>
                        <div class="post_wrapper">
                            <div class="post_thumb">
                                <a href="blog-details.html"><img src={% static "assets/img/blog/comment2.png.jpg" %} alt=""></a>
                            </div>
                            <div class="post_info">
                                <span><a href="#">demo</a> says:</span>
                                <a href="blog-details.html">Quisque semper nunc</a>
                            </div>
                        </div>
                        <div class="post_wrapper">
                            <div class="post_thumb">
                                <a href="blog-details.html"><img src={% static "assets/img/blog/comment2.png.jpg" %} alt=""></a>
                            </div>
                            <div class="post_info">
                                <span><a href="#">admin</a> says:</span>
                                <a href="blog-details.html">Quisque semper nunc</a>
                            </div>
                        </div>
                    </div>
                    <div class="widget_list widget_post">
                        <div class="widget_title">
                            <h3>Recent Posts</h3>
                        </div>
                        <div class="post_wrapper">
                            <div class="post_thumb">
                                <a href="blog-details.html"><img src={% static "assets/img/blog/blog12.jpg" %} alt=""></a>
                            </div>
                            <div class="post_info">
                                <h4><a href="blog-details.html">Blog image post</a></h4>
                                <span>March 16, 2018 </span>
                            </div>
                        </div>
                        <div class="post_wrapper">
                            <div class="post_thumb">
                                <a href="blog-details.html"><img src={% static "assets/img/blog/blog13.jpg" %} alt=""></a>
                            </div>
                            <div class="post_info">
                                <h4><a href="blog-details.html">Post with Gallery</a></h4>
                                <span>March 16, 2018 </span>
                            </div>
                        </div>
                        <div class="post_wrapper">
                            <div class="post_thumb">
                                <a href="blog-details.html"><img src={% static "assets/img/blog/blog14.jpg" %} alt=""></a>
                            </div>
                            <div class="post_info">
                                <h4><a href="blog-details.html">Post with Audio</a></h4>
                                <span>March 16, 2018 </span>
                            </div>
                        </div>
                        <div class="post_wrapper">
                            <div class="post_thumb">
                                <a href="blog-details.html"><img src={% static "assets/img/blog/blog15.jpg" %} alt=""></a>
                            </div>
                            <div class="post_info">
                                <h4><a href="blog-details.html">Post with Video</a></h4>
                                <span>March 16, 2018 </span>
                            </div>
                        </div>
                    </div>
                    <div class="widget_list widget_categories">
                        <div class="widget_title">
                            <h3>Categories</h3>
                        </div>
                        <ul>
                            <li><a href="#">Audio</a></li>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Gallery</a></li>
                            <li><a href="#">Image</a></li>
                            <li><a href="#">Other</a></li>
                            <li><a href="#">Travel</a></li>
                        </ul>
                    </div>
                    <div class="widget_list widget_tag">
                        <div class="widget_title">
                            <h3>Tag products</h3>
                        </div>
                        <div class="tag_widget">
                            <ul>
                                <li><a href="#">asian</a></li>
                                <li><a href="#">brown</a></li>
                                <li><a href="#">euro</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--blog area end-->

<!--blog pagination area start-->
<div class="blog_pagination">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="pagination">
                    <ul>
                        <li class="current">1</li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li class="next"><a href="#">next</a></li>
                        <li><a href="#">>></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--blog pagination area end-->


{% endblock %}