blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_view, name='blog'),
    path('<int:id>/', views.blog_details, name='blog_details'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

django_shopik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import login_view, logout_view, registration_view
from shop.views import shop_search

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls')),
    path('search/<str:sear>/', shop_search, name='shop_search'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop, name='shop_list'),
    # path('search/<str:sear>/', views.shop_search, name='shop_search'),
    path('<int:id>/', views.shop_category, name='shop_category'),
    path('<int:id>/<int:id_cat>/', views.shop_full, name='shop_full'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

wishlist/urls.py
from django.urls import path
from . import views


app_name = 'wishlist'

urlpatterns = [
    path('', views.wish_detail, name='wish_detail'),
    path('add/<int:product_id>/', views.wish_add, name='wish_add'),
    path('remove/<int:product_id>/', views.wish_remove, name='wish_remove'),
]

wishlist/models.py
from django.db import models

# Create your models here.

wishlist/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET
from cart.cart import Cart
from shop.models import Product, Category, Subcategory

from .wish import Wish

@require_GET
def wish_add(request, product_id):
    wish = Wish(request)
    product = get_object_or_404(Product, id=product_id)
    wish.add(product=product)
    return redirect('wishlist:wish_detail')

def wish_remove(request, product_id):
    wish = Wish(request)
    product = get_object_or_404(Product, id=product_id)
    wish.remove(product)
    return redirect('wishlist:wish_detail')

def wish_detail(request):
    wish = Wish(request)
    cart = Cart(request)
    categories = Category.objects.filter(is_visible=True)
    subcategories = Subcategory.objects.filter(is_visible=True)
    return render(request, 'wishlist.html', {'wish': wish, 'categories': categories, 'cart': cart, 'subcategories': subcategories})

wishlist/templates/wishlist.html
{% extends 'index.html' %}
{% load static %}
{% block site_content %}


    <!--breadcrumbs area start-->
    <div class="breadcrumbs_area">
    </div>
       <div class="breadcrumbs_area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb_content">
                        <h3>Wishlist</h3>
                        <ul>
                            <li><a href="{% url "shop:shop_list" %}">home</a></li>
                            <li>Wishlist</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs area end-->


    <!--wishlist area start -->
    <div class="wishlist_area mt-100">
        <div class="container">
            <form action="#">
                <div class="row">
                    <div class="col-12">
                        <div class="table_desc wishlist">
                            <div class="cart_page table-responsive">
                                <table>
                                    <thead>
                                        <tr>
                                            <th class="product_remove">Delete</th>
                                            <th class="product_thumb">Image</th>
                                            <th class="product_name">Product</th>
                                            <th class="product-price">Price</th>
                                            <th class="product_total">Add To Cart</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in wish %}
                                            {% with product=item.product %}
                                                <tr>
                                                    <td class="product_remove"><a href="{% url "wishlist:wish_remove" product.id %}">X</a></td>
                                                    <td class="product_thumb"><a href="{{ product.get_absolute_url }}"><img
                                                                src={{ product.image.url }} alt=""></a></td>
                                                    <td class="product_name"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                                                    <td class="product-price">{{ product.price }}</td>
                                                    <td class="product_total"><a href="{% url "cart:cart_add" product.id %}">Add To Cart</a></td>
                                                </tr>
                                            {% endwith %}
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>

            </form>

        </div>
    </div>
    <!--wishlist area end -->




{% endblock %}