blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_view, name='blog'),
    path('<int:id>/', views.blog_details, name='blog_details'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

django_shopik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import login_view, logout_view, registration_view
from shop.views import shop_search

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls')),
    path('search/<str:sear>/', shop_search, name='shop_search'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop, name='shop_list'),
    # path('search/<str:sear>/', views.shop_search, name='shop_search'),
    path('<int:id>/', views.shop_category, name='shop_category'),
    path('<int:id>/<int:id_cat>/', views.shop_full, name='shop_full'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

wishlist/urls.py
from django.urls import path
from . import views


app_name = 'wishlist'

urlpatterns = [
    path('', views.wish_detail, name='wish_detail'),
    path('add/<int:product_id>/', views.wish_add, name='wish_add'),
    path('remove/<int:product_id>/', views.wish_remove, name='wish_remove'),
]

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    position = models.PositiveSmallIntegerField(unique=True)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}: {self.position}'

    class Meta:
        ordering = ('position', )

    def get_absolute_url(self):
        return reverse("shop:shop_category", args=[self.id])


class Subcategory(models.Model):
    name = models.CharField(max_length=50, unique=True)
    position = models.PositiveSmallIntegerField(unique=True)
    is_visible = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}: {self.position}'

    class Meta:
        ordering = ('position', )

    def get_absolute_url(self):
        return reverse("shop:shop_full", args=[self.id, self.category.id])


class Brand(models.Model):
    name = models.CharField(max_length=50, unique=True)
    position = models.PositiveSmallIntegerField(unique=True)
    description = models.TextField(max_length=200, blank=True)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ('position', )


class Product(models.Model):
    name = models.CharField(max_length=100, db_index=True, unique=True)
    slug = models.SlugField(max_length=100, db_index=True)
    code_self = models.CharField(max_length=20, unique=True, blank=True)
    position = models.PositiveSmallIntegerField()
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    in_brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=200, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_visible = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    on_sale = models.BooleanField(default=False)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'), )

    def __str__(self):
        return f'{self.name}  {self.price}'

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])


class ProductsPhoto(models.Model):
    id_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('id_product', )

    def __str__(self):
        return f'{self.id_product}  {self.image}'

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address_street = models.CharField(max_length=50)
    address_apartment = models.CharField(max_length=50)
    address_city = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=20)
    email = models.EmailField()
    phone = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

shop/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate


User = get_user_model()


class Search(forms.Form):
    sear = forms.CharField(widget=forms.TextInput(attrs={'type': "text", 'placeholder': "Search product."}))

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET

from shop.models import Product, Category, Subcategory

from .cart import Cart

@require_GET
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product, quantity=1, update_quantity=False)
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    categories = Category.objects.filter(is_visible=True)
    subcategories = Subcategory.objects.filter(is_visible=True)
    return render(request, 'cart.html', {'cart': cart, 'categories': categories, 'subcategories': subcategories})

shop/views.py
from django.shortcuts import get_object_or_404, render
from cart.cart import Cart
from .models import Product, Category, Subcategory, Brand
from about.models import CustomersSays
from .forms import Search



def shop(request):
    cart = Cart(request)
    customers_saya = CustomersSays.objects.filter(is_visible=True)
    categories = Category.objects.filter(is_visible=True)
    sale_all = Product.objects.filter(on_sale=True)
    products = Product.objects.filter(is_visible=True)
    subcategories = Subcategory.objects.filter(is_visible=True)
    return render(request, 'shop.html', context={
        'sale_all': sale_all,
        'customers_saya': customers_saya,
        'products': products,
        'cart': cart,
        'categories': categories,
        'subcategories': subcategories,
    })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, is_visible=True)
    categories = Category.objects.filter(is_visible=True)
    subcategories = Subcategory.objects.filter(is_visible=True)
    cart = Cart(request)
    return render(request,
                  'product-details.html',
                  {'product': product,
                   'categories': categories,
                   'cart': cart,
                   'subcategories': subcategories},

                  )


def shop_full(request, id, id_cat):
    products = Product.objects.filter(is_visible=True, subcategory=id)
    categories = Category.objects.filter(is_visible=True)
    subcategories = Subcategory.objects.filter(is_visible=True)
    cart = Cart(request)
    return render(request,
                  'shop-fullwidth.html',
                  {'products': products,
                   'categories': categories,
                   'cart': cart,
                   'subcategories': subcategories},
                  )


def shop_category(request, id):
    products = Product.objects.filter(is_visible=True, subcategory__category=id)
    categories = Category.objects.filter(is_visible=True)
    subcategories = Subcategory.objects.filter(is_visible=True)
    cart = Cart(request)
    return render(request,
                  'shop-fullwidth.html',
                  {'products': products,
                   'categories': categories,
                   'cart': cart,
                   'subcategories': subcategories},
                  )


def shop_search(request, sear):
    form = Search(request.POST or None)
    # sear1 = form.sear
    product_all = Product.objects.filter(is_visible=True)
    products = []
    sear = sear.lower()
    for produсt in product_all:
        prod = produсt.name.lower()
        if prod.find(sear) != -1:
            products.append(produсt)
    categories = Category.objects.filter(is_visible=True)
    subcategories = Subcategory.objects.filter(is_visible=True)
    cart = Cart(request)
    return render(request,
                  'shop-fullwidth.html',
                  {'products': products,
                   'categories': categories,
                   'cart': cart,
                   'subcategories': subcategories},
                  )

shop/templates/cart.html
{% extends 'index.html' %}
{% load static %}
{% block site_content %}

    <!--shopping cart area start -->
<div class="shopping_cart_area mt-100">
    <div class="container">
        <form action="#">
            <div class="row">
                <div class="col-12">
                    <div class="table_desc">
                        <div class="cart_page table-responsive">
                            <table>
                                <thead>
                                    <tr>
                                        <th class="product_remove">Delete</th>
                                        <th class="product_thumb">Image</th>
                                        <th class="product_name">Product</th>
                                        <th class="product-price">Price</th>
                                        <th class="product_quantity">Quantity</th>
                                        <th class="product_total">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                        {% with product=item.product %}
                                            <tr>
                                                <td class="product_remove"><a href="{% url "cart:cart_remove" product.id %}"><i class="fa fa-trash-o"></i></a>
                                                </td>
                                                <td class="product_thumb"><a href="{{ product.get_absolute_url }}"><img
                                                            src={{ product.image.url }} alt=""></a></td>
                                                <td class="product_name"><a href="#">{{ product.name }}</a></td>
                                                <td class="product-price">{{ product.price }}</td>
                                                <td class="product_quantity"><label>Quantity</label> <input min="1"
                                                        max="100" value="{{ item.quantity }}" type="number"></td>
                                                <td class="product_total">{{ item.total_price }}</td>

                                            </tr>
                                        {% endwith %}
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="cart_submit">
                            <button type="submit">update cart</button>
                        </div>
                    </div>
                </div>
            </div>

            <!--coupon code area start-->
            <div class="coupon_area">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="coupon_code right">
                            <h3>Cart Totals</h3>
                            <div class="coupon_inner">
                                <div class="cart_subtotal">
                                    <p>Subtotal</p>
                                    <p class="cart_amount">{{ cart.get_total_price }}</p>
                                </div>
                                <div class="cart_subtotal ">
                                    <p>Shipping</p>
                                    <p class="cart_amount"><span>Flat Rate:</span> £255.00</p>
                                </div>
                                <a href="#">Calculate shipping</a>

                                <div class="cart_subtotal">
                                    <p>Total</p>
                                    <p class="cart_amount">£215.00</p>
                                </div>
                                <div class="checkout_btn">
                                    <a href="#">Proceed to Checkout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--coupon code area end-->
        </form>
    </div>
</div>
    <!--shopping cart area end -->

{% endblock %}

shop/templates/product-details.html
{% extends 'index.html' %}
{% load static %}
{% block site_content %}
    <!--product details start-->
    <div class="product_details mt-100 mb-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="product-details-tab">
                        <div id="img-1" class="zoomWrapper single-zoom">
                            <a href="#">
                                <img id="zoom1" src={{ product.image.url }}
                                    data-zoom-image={{ product.image.url }} alt="big-1">
                            </a>
                        </div>
                        <div class="single-zoom-thumb">
                            <ul class="s-tab-zoom owl-carousel single-product-active" id="gallery_01">
                                <li>
                                    <a href="#" class="elevatezoom-gallery active" data-update=""
                                        data-image="assets/img/product/productbig4.jpg"
                                        data-zoom-image="assets/img/product/productbig4.jpg">
                                        <img src={% static "assets/img/product/productbig4.jpg" %} alt="zo-th-1" />
                                    </a>

                                </li>
                                <li>
                                    <a href="#" class="elevatezoom-gallery active" data-update=""
                                        data-image="assets/img/product/productbig1.jpg"
                                        data-zoom-image="assets/img/product/productbig1.jpg">
                                        <img src={% static "assets/img/product/productbig1.jpg" %} alt="zo-th-1" />
                                    </a>

                                </li>
                                <li>
                                    <a href="#" class="elevatezoom-gallery active" data-update=""
                                        data-image="assets/img/product/productbig2.jpg"
                                        data-zoom-image="assets/img/product/productbig2.jpg">
                                        <img src={% static "assets/img/product/productbig2.jpg" %} alt="zo-th-1" />
                                    </a>

                                </li>
                                <li>
                                    <a href="#" class="elevatezoom-gallery active" data-update=""
                                        data-image="assets/img/product/productbig3.jpg"
                                        data-zoom-image="assets/img/product/productbig3.jpg">
                                        <img src={% static "assets/img/product/productbig3.jpg" %} alt="zo-th-1" />
                                    </a>

                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="product_d_right">
                        <form action="#">
                            <h1>{{ product.name }}</h1>
                            <div class="price_box">
                                <span class="current_price">{{ product.price }}</span>
                            </div>
                            <div class="product_desc">
                                <p>{{ product.description }}</p>
                            </div>
                            <div class="product_variant quantity">
                                <a href="{% url "cart:cart_add" product.id %}"
                                class="button" type="submit">add to cart</a>

                            </div>
                            <div class="product_meta">
                                <span>Category: <a href="#">{{ product.subcategory }}</a></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--product details end-->

{% endblock %}

shop/templates/products.html
{% load static %}

<div class="product_area product_style2">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="section_title">
                        <h2>Featured Products</h2>
                    </div>
                </div>
            </div>
            <div class="product_style2_ocntainer">
                <div class="row">
                    <div class="product_carousel product2_column5 owl-carousel">
                        {% for product in products %}
                             <div class="col-lg-3">
                                <div class="product_items">
                                    <article class="single_product">
                                    <figure>
                                        <div class="product_thumb">
                                            <a class="primary_img" href="{{ product.get_absolute_url }}"><img
                                                    src={{ product.image.url }} alt=""></a>
                                            <div class="label_product">
                                                <span class="label_sale">{{ product.in_brand }}</span>
                                            </div>
                                            <div class="action_links">
                                                <ul>
                                                    <li class="add_to_cart"><a href="{% url "cart:cart_add" product.id %}" title="Add to кошик"><i
                                                                class="icon-shopping-bag"></i></a></li>
                                                    <li class="compare"><a href="#" title="Add to Compare"><i
                                                                class="icon-sliders"></i></a></li>
                                                    <li class="wishlist"><a href="{% url "wishlist:wish_add" product.id %}"
                                                            title="Add to Wishlist"><i class="icon-heart"></i></a></li>
                                                    <li class="quick_button"><a href="#" data-toggle="modal"
                                                            data-target="#modal_box" title="quick view"> <i
                                                                class="icon-eye"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <figcaption class="product_content">
                                            <div class="product_rating">
                                                <ul>
                                                    <li><a href="#"><i class="icon-star"></i></a></li>
                                                    <li><a href="#"><i class="icon-star"></i></a></li>
                                                    <li><a href="#"><i class="icon-star"></i></a></li>
                                                    <li><a href="#"><i class="icon-star"></i></a></li>
                                                    <li><a href="#"><i class="icon-star"></i></a></li>
                                                </ul>
                                            </div>
                                            <h4 class="product_name"><a href="product-details.html">{{ product.name }}</a></h4>
                                            <div class="price_box">
                                                <span class="current_price">{{ product.price }}</span>
                                                <span class="old_price">£74.00</span>
                                            </div>
                                        </figcaption>
                                    </figure>
                                </article>
                                </div>
                             </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>

shop/templates/shop-fullwidth.html
{% extends 'index.html' %}
{% load static %}
{% block site_content %}


<div class="shop_area shop_fullwidth mt-100 mb-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!--shop wrapper start-->
                <!--shop toolbar start-->
                <div class="shop_toolbar_wrapper">
                    <div class="shop_toolbar_btn">
                        <button data-role="grid_3" type="button" class=" btn-grid-3" data-toggle="tooltip"
                            title="3"></button>

                        <button data-role="grid_4" type="button" class="active btn-grid-4" data-toggle="tooltip"
                            title="4"></button>

                        <button data-role="grid_list" type="button" class="btn-list" data-toggle="tooltip"
                            title="List"></button>
                    </div>
                    <div class=" niceselect_option">
                        <form class="select_option" action="#">
                            <select name="orderby" id="short">

                                <option selected value="1">Sort by average rating</option>
                                <option value="2">Sort by popularity</option>
                                <option value="3">Sort by newness</option>
                                <option value="4">Sort by price: low to high</option>
                                <option value="5">Sort by price: high to low</option>
                                <option value="6">Product Name: Z</option>
                            </select>
                        </form>
                    </div>
                    <div class="page_amount">
                        <p>Showing 1–9 of 21 results</p>
                    </div>
                </div>
                <!--shop toolbar end-->
                <div class="row shop_wrapper grid_4">
                    {% for product in products %}
                        <div class="col-lg-3 col-md-4 col-12 ">
                        <article class="single_product">
                            <figure>
                                <div class="product_thumb">
                                    <a class="primary_img" href="{{ product.get_absolute_url }}"><img
                                            src={{ product.image.url }} alt=""></a>
                                    <div class="label_product">
                                        <span class="label_sale">{{ product.in_brand }}</span>
                                    </div>
                                    <div class="action_links">
                                        <ul>
                                            <li class="add_to_cart"><a href="{% url "cart:cart_add" product.id %}" title="Add to cart"><i
                                                        class="icon-shopping-bag"></i></a></li>
                                            <li class="compare"><a href="#" title="Add to Compare"><i
                                                        class="icon-sliders"></i></a></li>
                                            <li class="wishlist"><a href="{% url "wishlist:wish_add" product.id %}" title="Add to Wishlist"><i
                                                        class="icon-heart"></i></a></li>
                                            <li class="quick_button"><a href="#" data-toggle="modal"
                                                    data-target="#modal_box" title="quick view"> <i
                                                        class="icon-eye"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="action_links list_action">
                                        <ul>
                                            <li class="quick_button"><a href="#" data-toggle="modal"
                                                    data-target="#modal_box" title="quick view"> <i
                                                        class="icon-eye"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="product_content grid_content">
                                    <div class="product_price_rating">
                                        <h4 class="product_name"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                                        <div class="price_box">
                                            <span class="current_price">{{ product.price }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="product_content list_content">
                                    <h4 class="product_name"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                    </h4>
                                    <div class="price_box">
                                        <span class="current_price">{{ product.price }}</span>
                                    </div>
                                    <div class="product_desc">
                                        <p>{{ product.description }}</p>
                                    </div>
                                    <div class="action_links list_action_right">
                                        <ul>
                                            <li class="add_to_cart"><a href="{% url "cart:cart_add" product.id %}" title="Add to cart">Add to
                                                    cart</a></li>
                                            <li class="wishlist"><a href="{% url "wishlist:wish_add" product.id %}" title="Add to Wishlist"><i
                                                        class="icon-heart"></i></a></li>
                                            <li class="compare"><a href="#" title="Add to Compare"><i
                                                        class="icon-sliders"></i></a></li>

                                        </ul>
                                    </div>
                                </div>
                            </figure>
                        </article>
                    </div>
                    {% endfor %}
                </div>

                <div class="shop_toolbar t_bottom">
                    <div class="pagination">
                        <ul>
                            <li class="current">1</li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li class="next"><a href="#">next</a></li>
                            <li><a href="#">>></a></li>
                        </ul>
                    </div>
                </div>
                <!--shop toolbar end-->
                <!--shop wrapper end-->
            </div>
        </div>
    </div>
</div>


{% endblock %}

shop/templates/slider.html
{% load static %}
<!--slider area start-->
<section class="slider_section slider_s_two">
        <div class="slider_area owl-carousel">
            {% for sale in sale_all %}
                <div class="single_slider d-flex align-items-center" data-bgimg={{ sale.image.url }}>
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <div class="slider_content">
                                    <span>Розпродаж </span>
                                    <h1>Найкраще <br> <span>по ціні</span></h1>
                                    <p>Discount 20% для всіх </p>
                                    <a class="button" href="{{ sale.get_absolute_url }}">{{ sale.name }} </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
</section>
<!--slider area end-->